### ISSUE TITLE
`A` vs `i`

### ISSUE THREAD

**Issue by Y-Less** [bmisiak/samp-precise-timers#1]
Array lengths in all other implementations, including other timer plugins, includes, and other natives like `CallRemoteFunction` and `CallLocalFunction` are passed using `i` (or `d` of course):

```pawn
SetTimerEx("func", 1000, false, "ai", arr, sizeof (arr));
```

It would be nice if this was compatible with everything else.

**Comment by aventez** [comment]
Yes, but it accepts only one dimension, to pass a 2D array we need to use 
`sizeof(array) + sizeof(array) * sizeof(array[])`

**Comment by Y-Less** [comment]
What's that got to do with it?

**Comment by bmisiak** [comment]
Fixed in the new release. Thank you for the feedback! ❤
