### ISSUE TITLE
Updating The Timer Duration

### ISSUE THREAD

**Issue by nexquery** [bmisiak/samp-precise-timers#12]
Hello, I noticed the timer ID increased when I stopped and restarted the timer. For these long-term servers, I think there may be problems in the future due to the limits. I want you to add a function to update the timer duration instead of stopping the timer and starting it again.

**Comment by bmisiak** [comment]
Hello. Thank you for the report.

Timer IDs do not actually increment blindly. The plugin uses a slotmap, so they receive the lowest unused ID.

The behavior you were seeing stems from deferring the removal of a timer until the moment of its scheduled firing, so at any time there could be a few extra slots used but they get cleared regularly.
