### ISSUE TITLE
The amount of callback arguments passed (1) does not match the length of the list of types

### ISSUE THREAD

**Issue by Abyss-z94** [bmisiak/samp-precise-timers#14]
I got errors while running precise timers on my script, how can i fix it?

samp-precise-timers error: The amount of callback arguments passed (1) does not match the length of the list of types (3).

timer using:

Controller[playerid][km_Timer][keyid] = SetPreciseTimer("Key_Moving", Controller[playerid][km_Moving_Time], false, "ii", playerid, keyid);

Controller[playerid][km_Timer][keyid] = SetPreciseTimer("Key_Moving_Ex", Controller[playerid][km_Moving_Time], false, "ii", playerid, keyid);

Controller[playerid][km_ReUpdate_Timer] = SetPreciseTimer("OnPlayerFinishController", 100, true, "iiiiiiii", playerid, Controller[playerid][km_ID], Controller[playerid][km_Key_Pressed], Controller[playerid][km_Key_Missed], Controller[playerid][km_Perfect_Count], Controller[playerid][km_Great_Count], Controller[playerid][km_Cool_Count], Controller[playerid][km_Bad_Count]);

Controller[playerid][km_Generator_Timer] = SetPreciseTimer("ControllerGenerator", time_per_key, true, "i", playerid);

Controller[playerid][km_Reset_Miss_Timer] = SetPreciseTimer("ResetMissNotice", 500, false, "i", playerid);

Controller[playerid][km_Holding_Timer] = SetPreciseTimer("CheckingPlayerHoldingKeys", 10, true, "iii", playerid, keyid, lr);

Controller[playerid][km_Reset_Miss_Timer] = SetPreciseTimer("ResetMissNotice", 500, false, "i", playerid);

**Comment by bmisiak** [comment]
It's just a helpful message to let you know the plugin is not receiving the expected amount of parameters. In this case, somewhere you called `SetPreciseTimer` with three argument letters, like `"iii"`, but it only received one variable.

This one has three declared arguments (`"iii"`)  but it does seem to be getting three variables as well. Does the message go away when you remove this line? 
```
Controller[playerid][km_Holding_Timer] = SetPreciseTimer("CheckingPlayerHoldingKeys", 10, true, "iii", playerid, keyid, lr);
```

**Comment by Abyss-z94** [comment]
Ya, it's does, i've added them to the server, replacing the default SetTimerEx function, they work fine with these Timer set up to run automatically, repeatedly (like: `SetPreciseTimer("Server_Update", 1000, true)`). But there is an error if I apply it to the timers that are used over and over manually like:

```
Character_Timer[playerid][tm_Business_Clothes_Door] = SetPreciseTimer("Business_Clothes_Door", 500, false, "iii", playerid, 1, 1);

forward Business_Clothes_Door(playerid, level, step);
public Business_Clothes_Door(playerid, level, step)
{
if(Character_Timer[playerid][tm_Business_Clothes_Door] != INVALID_NUMBER) Stop_Precise:(Character_Timer[playerid][tm_Business_Clothes_Door]); // #define 	Stop_Precise:(%0) 		DeletePreciseTimer(%0); %0 = -1
Character_Timer[playerid][tm_Business_Clothes_Door] = SetPreciseTimer("Business_Clothes_Door", 800, false, "iii", playerid, level + 1, step + 1);
}
```
It's gonna stop working if server got many PreciseTimer are running
