### ISSUE TITLE
[12:58:01] [Info] samp-precise-timers error: Error executing timer callback: Index out of bounds

### ISSUE THREAD

**Issue by PolishDywan** [bmisiak/samp-precise-timers#15]
The plugin is not compatible with open.mp

**Comment by PateeerQ** [comment]
since u were using open.mp, you don't need this

**Comment by bmisiak** [comment]
Actually the implementation in this plugin is not vulnerable to iterator invalidation by the callback, and doesn't iterate over all timers on every tick unlike [openmp's implementation](https://github.com/openmultiplayer/open.mp/blob/master/Server/Components/Timers/timers_main.cpp) so you could still benefit from it if you have a lot of timers : ) Are you still having issues on 3.1.1?
