### ISSUE TITLE
Problem in v2.1.0 (Error executing timer callback: Index out of bounds)

### ISSUE THREAD

**Issue by donnie090** [bmisiak/samp-precise-timers#18]
This problem exists only in 2.1.0, in version 2.0.2, this problem does not exist

create timer:
`gPlayerSecondTimer[ playerid ] = SetPreciseTimer("UpdatePlayerTimer", 1000, true, "d", playerid);`

consol (after creating timer):
`[03:43:06] samp-precise-timers error: Error executing timer callback: Index out of bounds`

**Comment by raedman90** [comment]
Did you come up with a solution?

**Comment by donnie090** [comment]
> Did you come up with a solution?

Yes, just don't use it and switch to OMP

**Comment by donnie090** [comment]
..
