### ISSUE TITLE
[sampgdk:warning] Native function not found

### ISSUE THREAD

**Issue by Hoxxy** [bmisiak/samp-precise-timers#7]
There seems to be a problem with the Linux version.

```
[sampgdk:warning] Native function not found: GetPlayerInterior
[sampgdk:warning] Native function not found: GetPlayerVirtualWorld
[sampgdk:warning] Native function not found: GetPlayerState
```

This only happens when loading this plugin and only on Linux.
Other plugins I use and their order is as follows: crashdetect.so mysql.so samp-previse-timers.so sscanf.so streamer.so regex.so
All of them are on their latest versions. Removing this plugin fixes the issue.

**Comment by ghost** [comment]
its missing lack of implementation of the functions to the plugin. hopefully there are implemented in the near future

**Comment by nathanramli** [comment]
Hello @bmisiak 
I noticed that you make some commits.
Did you fixed this issue?

**Comment by bmisiak** [comment]
Hi Nathan.

I did! The plugin now uses a newer version of samp-rs which works around
`sampgdk`’s incompatible behavior. I just need to recompile and release it.

In the meantime, you can try compiling it yourself by following the
instructions. On linux, make sure you have `build-essential` and/or
`gcc-multilib` installed.

**Comment by nathanramli** [comment]
Glad to hear that, thanks for fixing this issue.

I will try to recompile it.

**Comment by bmisiak** [comment]
Fixed in 2.0.1!

**Comment by nathanramli** [comment]
@bmisiak May i know why there is no windows version on your latest release?

**Comment by bmisiak** [comment]
@nathanramli I didn't have access to a Windows machine. Now that I set up CI, the windows .dll is included again. Have fun!

**Comment by nathanramli** [comment]
Okay,
Thank you so much.
